### ISSUE TITLE
Regression in 0.9.6

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#1634]
[pyGaussDCA](https://github.com/ElofssonLab/pyGaussDCA) has stopped working with pythran 0.9.6, but works with 0.9.5.

I believe the root cause is this error message:

```
  /home/david/.virtualenv/py37/lib/python3.7/site-packages/pythran/pythonic/include/__builtin__/RuntimeError.hpp:11:27: error: ‘RuntimeError’ is not a member of ‘{anonymous}::pythonic::builtins’                                                                                                                                                                                          
     11 |   PYTHONIC_EXCEPTION_DECL(RuntimeError)                                                                                                                                             
        |                           ^~~~~~~~~~~~           
```

**Comment by serge-sans-paille** [comment]
Do you have a minimal reproducer?

**Comment by serge-sans-paille** [comment]
I compiled the master branch of your repo with the master branch of pythran without any issue :-/

**Comment by Dapid** [comment]
This is weird. I had reports for several users, I replicated it on my machine, but while I was trying to track it down, the error disapeared. I guess some other package got updated?

Also, I'd swear Travis was failing too in the Pythran master branch, but it is all green.

I'll close it then.
