### ISSUE TITLE
Compilation error in linux on array[array > long]

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#896]
The following code does not compile in pythran 0.8.5 (linux)
```
import numpy as np

#pythran export test(int[])
def test(peaks):
    peaks = peaks[peaks>30] # <- does not compiles
    # peaks = np.array(peaks[peaks>30]) # <- compiles in linux, not macos
    # peaks = np.array(peaks[peaks>30],dtype=int) # <- compiles everywhere
    lastBin = 0
    for peak in peaks:
        lastBin = peak
    return lastBin

# if __name__ == '__main__':
#     test(np.array([0,1,2,3]))
```
Error log attached
[error.txt](https://github.com/serge-sans-paille/pythran/files/1992441/error.txt)

**Comment by serge-sans-paille** [comment]
Should be fixed by #899

**Comment by jeanlaroche** [comment]
Confirmed fixed by #899 both in linux _**and**_ MacOS! Yepee!!!
