### ISSUE TITLE
Compilation error error: implicit instantiation of undefined template 'std::tuple_element<0, long>'

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#2332]
Trying to compile this code with the current pythran version:
```
#pythran export test (int)

def FuncA(N):
    AA = [[0.0]] * N
    BB = [AA]
    CC = [AA]
    DD = 0
    retTuple = tuple([[BB], [CC], [DD]])
    FuncB(retTuple)      #< - remove this and the error disappears.
    return retTuple

def FuncB(retTuple):
    retTuple[2][0] = 5

def test(N):
    retTuple = FuncA(N)
    print(retTuple)
```
Yields:
```
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:77:31: error: implicit instantiation of undefined template 'std::tuple_element<0, long>'
        typedef typename std::tuple_element<0,typename std::remove_reference<__type24>::type>::type __type25;
                              ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:128:5: note: in instantiation of template class '(anonymous namespace)::__pythran_BUG::FuncA::type<long>' requested here
    typename FuncA::type<argument_type0>::result_type FuncA::operator()(argument_type0 N) const
    ^
/Users/jlaroche/ua_conda_env-Darwin.arm64/lib/python3.8/site-packages/pythran/pythonic/include/types/assignable.hpp:42:47: note: while substituting explicitly-specified template arguments into function template 'operator()'
      -> decltype(std::forward<F>(f).template operator()<by_val_t<Args>...>(
                                              ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:187:44: note: while substituting deduced template arguments into function template 'call' [with F = FuncA, Args = <long &>]
      pythonic::builtins::functor::print{}(pythonic::types::call(FuncA(), N));
                                           ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:200:65: note: in instantiation of function template specialization '(anonymous namespace)::__pythran_BUG::test::operator()<long>' requested here
                                auto res = __pythran_BUG::test()(N);
                                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple_dir/tuple_element.h:26:62: note: template is declared here
template <size_t _Ip, class _Tp> struct _LIBCPP_TEMPLATE_VIS tuple_element;
                                                             ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:80:31: error: implicit instantiation of undefined template 'std::tuple_element<0, long>'
        typedef typename std::tuple_element<0,typename std::remove_reference<__type27>::type>::type __type28;
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple_dir/tuple_element.h:26:62: note: template is declared here
template <size_t _Ip, class _Tp> struct _LIBCPP_TEMPLATE_VIS tuple_element;
                                                             ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:87:31: error: implicit instantiation of undefined template 'std::tuple_element<0, long>'
        typedef typename std::tuple_element<0,typename std::remove_reference<__type34>::type>::type __type35;
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple_dir/tuple_element.h:26:62: note: template is declared here
template <size_t _Ip, class _Tp> struct _LIBCPP_TEMPLATE_VIS tuple_element;
                                                             ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:90:31: error: implicit instantiation of undefined template 'std::tuple_element<0, long>'
        typedef typename std::tuple_element<0,typename std::remove_reference<__type37>::type>::type __type38;
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple_dir/tuple_element.h:26:62: note: template is declared here
template <size_t _Ip, class _Tp> struct _LIBCPP_TEMPLATE_VIS tuple_element;
                                                             ^
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:187:44: error: no matching function for call to 'call'
      pythonic::builtins::functor::print{}(pythonic::types::call(FuncA(), N));
                                           ^~~~~~~~~~~~~~~~~~~~~
/var/folders/2p/dngs2w5x6tn3lw2jqsnl42_80000gp/T/tmpz1p0j1f8.cpp:200:65: note: in instantiation of function template specialization '(anonymous namespace)::__pythran_BUG::test::operator()<long>' requested here
                                auto res = __pythran_BUG::test()(N);
                                                                ^
/Users/jlaroche/ua_conda_env-Darwin.arm64/lib/python3.8/site-packages/pythran/pythonic/include/types/assignable.hpp:41:22: note: candidate template ignored: substitution failure [with F = (anonymous namespace)::__pythran_BUG::FuncA, Args = <long &>]: no matching member function for call to 'operator()'
  static inline auto call(F &&f, Args &&...args)
                     ^
```

The code works with pythran 17.0.0
This is on MacOS M1.
