### ISSUE TITLE
Unable to configure CC and CXX in pythranrc and gcc 7 bug with pythran+numpy

### ISSUE THREAD

**Issue by ashwinvis** [serge-sans-paille/pythran#687]
## System configuration
- Arch Linux
- gcc-7.1.1 and gcc-5.4.0
- numpy==1.13.0
- pythran==0.8.0
- python==2.7.13

First of all, allow me to rant that it should be mentioned somewhere in the README that pythran only works in a medium version gcc > 4.9 and gcc < 6(??). I lost quite a lot of time trying to pythranize with gcc==4.7.2 and gcc==7.1.1 (super old and super new) - does not work at all (for traceback, see https://paste.pound-python.org/show/bA0TjMrAWP54PcKOU375/ ).Thanks to folks at IRC channel #pythran I was able to figure this out. 
 
## Issue

Pythran works when I try

    $ CC=gcc-5 CXX=g++-5 pythran nd_local_maxima.py

on the test case.

However when I try to make this choice of compiler permanent by modifying your pythran-linux2.cfg template and putting it in $HOME/.pythranrc as follows:
````
[compiler]
defines=USE_GMP
undefs=
include_dirs=
libs=gmp gmpxx
library_dirs=
cflags=-std=c++11 -fno-math-errno -w -fwhole-program -fvisibility=hidden
ldflags=-fvisibility=hidden -Wl,-strip-all
blas=cblas
CC=gcc-5
CXX=g++-5
````
Note that, leaving `blas` option empty gave me some other weird error. On running:

    $ pythran nd_local_maxima.py -v

yields a type error.

````python
running build_ext
running build_src
build_src
building extension "nd_local_maxima" sources
build_src: building npy-pkg config files
new_compiler returns distutils.unixccompiler.UnixCCompiler
INFO     customize UnixCCompiler
customize UnixCCompiler using build_ext
********************************************************************************
distutils.unixccompiler.UnixCCompiler
linker_exe    = u'gcc-5'
compiler_so   = u'gcc-5 -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC'
archiver      = ['ar', 'rc']
preprocessor  = u'gcc-5 -E'
linker_so     = ['gcc', '-pthread', '-shared', '-Wl,-O1,--sort-common,--as-needed,-z,relro']
compiler_cxx  = u'g++-5'
ranlib        = None
compiler      = u'gcc-5 -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
libraries     = []
library_dirs  = ['/usr/lib']
include_dirs  = ['/usr/include/python2.7']
********************************************************************************
new_compiler returns distutils.unixccompiler.UnixCCompiler
INFO     customize UnixCCompiler
customize UnixCCompiler using build_ext
********************************************************************************
distutils.unixccompiler.UnixCCompiler
linker_exe    = u'gcc-5'
compiler_so   = u'gcc-5 -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC'
archiver      = ['ar', 'rc']
preprocessor  = u'gcc-5 -E'
linker_so     = ['gcc', '-pthread', '-shared', '-Wl,-O1,--sort-common,--as-needed,-z,relro']
compiler_cxx  = u'g++-5'
ranlib        = None
compiler      = u'gcc-5 -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
libraries     = []
library_dirs  = ['/usr/lib']
include_dirs  = ['/usr/include/python2.7']
********************************************************************************
Traceback (most recent call last):
  File "/scratch/avmo/opt/fluidsim-merge/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran/run.py", line 133, in run
    **compile_flags(args))
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran/toolchain.py", line 360, in compile_pythranfile
    **kwargs)
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran/toolchain.py", line 331, in compile_pythrancode
    **kwargs)
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran/toolchain.py", line 293, in compile_cxxcode
    output_binary, **kwargs)
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran/toolchain.py", line 263, in compile_cxxfile
    '--build-temp', buildtmp,
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 206, in run
    self._cxx_compiler = compiler.cxx_compiler()
  File "/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 633, in CCompiler_cxx_compiler
    cxx.compiler_so = [cxx.compiler_cxx[0]] + cxx.compiler_so[1:]
TypeError: can only concatenate list (not "unicode") to list
````

**Comment by serge-sans-paille** [comment]
Hi @ashwinvis,

> First of all, allow me to rant that it should be mentioned somewhere in the README that pythran only works in a medium version gcc > 4.9 and gcc < 6(??).

Rant accepted. the gcc > 4.9, has documented somewhere here http://pythonhosted.org/pythran/MANUAL.html. I should make this more explicit; The gcc < 6 is a bug, I'll try to reproduce this.

I'll investigate the config file error too, that should not happen.

**Comment by serge-sans-paille** [comment]
The blas error has been fixed in 2766e0ac890cf2c3ae2ff7f9fb865ada00c403b7, the problem no longer happens in master.

**Comment by serge-sans-paille** [comment]
And everything works fine with gcc 6, gcc 7 is not yes in debain testing, can't assert that.

**Comment by ashwinvis** [comment]
@serge-sans-paille, thanks for the prompt reply :).

gcc 7 is the default compiler for Arch Linux, with gcc 5 maintained in community repo. Maybe the AUR maintainer @xantares can verify this?

Looking forward for a fix for the config file.

**Comment by ashwinvis** [comment]
After that fix, I am able to pythranize with no hiccups

```
running build_ext
running build_src
build_src
building extension "nd_local_maxima" sources
build_src: building npy-pkg config files
new_compiler returns distutils.unixccompiler.UnixCCompiler
INFO     customize UnixCCompiler
customize UnixCCompiler using build_ext
********************************************************************************
distutils.unixccompiler.UnixCCompiler
linker_exe    = ['gcc-5']
compiler_so   = ['gcc-5', '-fno-strict-aliasing', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-DNDEBUG', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-fPIC']
archiver      = ['ar', 'rc']
preprocessor  = ['gcc-5', '-E']
linker_so     = ['gcc', '-pthread', '-shared', '-Wl,-O1,--sort-common,--as-needed,-z,relro']
compiler_cxx  = ['g++-5']
ranlib        = None
compiler      = ['gcc-5', '-fno-strict-aliasing', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-DNDEBUG', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong']
libraries     = []
library_dirs  = ['/usr/lib']
include_dirs  = ['/usr/include/python2.7']
********************************************************************************
new_compiler returns distutils.unixccompiler.UnixCCompiler
INFO     customize UnixCCompiler
customize UnixCCompiler using build_ext
********************************************************************************
distutils.unixccompiler.UnixCCompiler
linker_exe    = ['gcc-5']
compiler_so   = ['gcc-5', '-fno-strict-aliasing', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-DNDEBUG', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-fPIC']
archiver      = ['ar', 'rc']
preprocessor  = ['gcc-5', '-E']
linker_so     = ['gcc', '-pthread', '-shared', '-Wl,-O1,--sort-common,--as-needed,-z,relro']
compiler_cxx  = ['g++-5']
ranlib        = None
compiler      = ['gcc-5', '-fno-strict-aliasing', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-DNDEBUG', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong']
libraries     = []
library_dirs  = ['/usr/lib']
include_dirs  = ['/usr/include/python2.7']
********************************************************************************
building 'nd_local_maxima' extension
compiling C++ sources
C compiler: g++-5 -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC

creating /tmp/tmpwOTJnz/tmp
compile options: '-DUSE_GMP -DENABLE_PYTHON_MODULE -D__PYTHRAN__=2 -I/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran-0.8.0-py2.7.egg/pythran -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
extra options: '-std=c++11 -fno-math-errno -w -fwhole-program -fvisibility=hidden'
g++-5: /tmp/tmppRpmDp.cpp
exec_command(['g++-5', '-fno-strict-aliasing', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-DNDEBUG', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector-strong', '-fPIC', '-DUSE_GMP', '-DENABLE_PYTHON_MODULE', '-D__PYTHRAN__=2', '-I/scratch/avmo/opt/fluidsim-merge/lib/python2.7/site-packages/pythran-0.8.0-py2.7.egg/pythran', '-I/usr/lib/python2.7/site-packages/numpy/core/include', '-I/usr/include/python2.7', '-c', '/tmp/tmppRpmDp.cpp', '-o', '/tmp/tmpwOTJnz/tmp/tmppRpmDp.o', '-std=c++11', '-fno-math-errno', '-w', '-fwhole-program', '-fvisibility=hidden'],)
Retaining cwd: /home/avmo/src/sandbox/pythran/pythran/tests/cases
_preserve_environment([])
_update_environment(...)
_update_environment(...)
g++-5 -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro /tmp/tmpwOTJnz/tmp/tmppRpmDp.o -L/usr/lib -lgmp -lgmpxx -lcblas -lpython2.7 -o /tmp/tmpEa0g3E/nd_local_maxima.so -fvisibility=hidden -Wl,-strip-all
exec_command(['g++-5', '-pthread', '-shared', '-Wl,-O1,--sort-common,--as-needed,-z,relro', '/tmp/tmpwOTJnz/tmp/tmppRpmDp.o', '-L/usr/lib', '-lgmp', '-lgmpxx', u'-lcblas', '-lpython2.7', '-o', '/tmp/tmpEa0g3E/nd_local_maxima.so', '-fvisibility=hidden', '-Wl,-strip-all'],)
Retaining cwd: /home/avmo/src/sandbox/pythran/pythran/tests/cases
_preserve_environment([])
_update_environment(...)
_update_environment(...)
INFO     Generated module: nd_local_maxima
INFO     Output: /home/avmo/src/sandbox/pythran/pythran/tests/cases/nd_local_maxima.so
```

**Comment by serge-sans-paille** [comment]
Concerning the g++-7.1 issue, that's a gcc bug, I reported it here:

    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81188

And it's being fixed!

**Comment by ashwinvis** [comment]
That's awesome... Now I can use the whole stack without any hiccups

**Comment by ashwinvis** [comment]
gcc has resolved your bug report, and your test cpp file compiles with no issue, with gcc-7.2.0

```cpp
template <class F>
struct C {
  F fast(long i) const;
  auto operator[](long i) const -> decltype(this->fast(i));
};

template <class F>
auto C<F>::operator[](long i) const -> decltype(this->fast(i)) {
  return fast(i);
}
```

However there is something else, as I still cannot pythranize the `nd_local_maxima.py` test case. See output here: https://paste.pound-python.org/show/Omi0eiJ3e1jtr6UmaWbd/

**Comment by serge-sans-paille** [comment]
... I'll make a minimal test case out of this and submit it again :-/

**Comment by serge-sans-paille** [comment]
@ashwinvis can you confirm the following test case does not compile?

```template <class Arg>
struct my_type {

  long fast(long i) const;
  long fast(long i) ;

  auto operator[](long i) const -> decltype(this->fast(i));

  template <class E>
  auto fast(E const &expr) const -> decltype(expr.any());
};


template <class Arg>
auto my_type<Arg>::operator[](long i) const -> decltype(this->fast(i))
{
  return fast(i);
}


```

**Comment by ashwinvis** [comment]
Do you have a bug in the test case?

```cpp
~ » g++ -std=c++11 -c test_gcc72.cpp
test_gcc72.cpp:14:13: error: expected initializer before ‘<’ token
 auto my_type<Arg>::operator[](long i) const -> decltype(this->fast(i))
             ^
~ » g++-5 -std=c++11 -c test_gcc72.cpp
test_gcc72.cpp:14:13: error: expected initializer before ‘<’ token
 auto my_type<Arg>::operator[](long i) const -> decltype(this->fast(i))
             ^
~ » g++ --version
g++ (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~ » g++-5 --version
g++-5 (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by serge-sans-paille** [comment]
It turns out to be a duplicated bug in gcc https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82311

**Comment by serge-sans-paille** [comment]
@ashwinvis #736 should make pythran header resilient to the gcc bug.

**Comment by ashwinvis** [comment]
I checked out #736 and yes, I was able to pythranize `nd_local_maxima.py` and also able to run `pytest test_ndarray.py` successfully. Since the test suite is pretty huge I did not try everything. See for logs if interested: http://dpaste.com/0D7ZYB5

**Comment by serge-sans-paille** [comment]
Closed by #736
