### ISSUE TITLE
icc compiler

### ISSUE THREAD

**Issue by svretina** [serge-sans-paille/pythran#892]
Hello, is there a way to have instead of gcc or g++ , the icc compiler for faster code? I didn't find anything in your doc. Thanks in advance.

**Comment by serge-sans-paille** [comment]
Unfortunately, although they claim the opposite, icc does not support C++11 correctly. An easy way to test would be to set ``CXX=icpc pythran test.py``, maybe they released a new version since my last test?

**Comment by paugier** [comment]
When I try to use Pythran with a quite recent version of icpc, I get:
```
exec_command(['icpc', '-fno-strict-aliasing', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-O3', '-Wall', '-axMIC_AVX512,CORE-AVX2,SSE4.2', '-O3', '-g', '-fPIC', '-diag-disable:remark,warning', '-axMIC_AVX512,CORE-AVX2,SSE4.2', '-O3', '-g', '-fPIC', '-diag-disable:remark,warning', '-fPIC', '-DENABLE_PYTHON_MODULE', '-D__PYTHRAN__=3', '-DENABLE_PYTHON_MODULE', '-D__PYTHRAN__=3', '-DPYTHRAN_BLAS_BLAS', '-DPYTHRAN_BLAS_BLAS', '-I/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran', '-I/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran', '-I/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/patch', '-I/panfs/panasas/softs/occigen/tools/python/3.6.3/intel/17.2/nompi/lib/python3.6/site-packages/numpy/core/include', '-I/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/patch', '-I/panfs/panasas/softs/occigen/tools/python/3.6.3/intel/17.2/nompi/lib/python3.6/site-packages/numpy/core/include', '-I/opt/software/occigen/tools/python/3.6.3/intel/17.2/nompi/include/python3.6m', '-c', '/tmp/tmpyv1zhfw1.cpp', '-o', '/tmp/tmpnbz8oh4x/tmp/tmpyv1zhfw1.o', '-std=c++11', '-fno-math-errno', '-w', '-fvisibility=hidden', '-fno-wrapv', '-std=c++11', '-fno-math-errno', '-w', '-fvisibility=hidden', '-fno-wrapv'],)
Retaining cwd: /panfs/panasas/cnt0022/egi2153/augier/tmp
_preserve_environment([])
_update_environment(...)
In file included from /panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/types/tuple.hpp(12),
                 from /panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/__builtin__/bool_.hpp(7),
                 from /panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/types/NoneType.hpp(8),
                 from /panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/types/slice.hpp(5),
                 from /panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/core.hpp(24),
                 from /tmp/tmpyv1zhfw1.cpp(1):
/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/types/ndarray.hpp(1127): error: declaration is incompatible with function template "auto <unnamed>::pythonic::types::__ndarray::<unnamed>::_build_gexpr<N>::operator()(const E &, const S &...)->decltype((<expression>))" (declared at line 728 of "/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/include/types/ndarray.hpp")
        auto _build_gexpr<N>::operator()(E const &a, S const &... slices)
```
and other similar errors.

@serge-sans-paille, is it really a C++11 support problem? Do you know which C++11 features is no well supported enough by icpc to compile Pythran C++ code?

See https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler

On clusters, people usually use the intel compilers, so it would be really good to be able to use these compilers or at least to document why it does not work.

**Comment by serge-sans-paille** [comment]
For the record, I already reported the issue: https://software.intel.com/en-us/forums/intel-c-compiler/topic/623633

**Comment by paugier** [comment]
Good news: simple examples without numpy now compile with recent versions of icpc.

Bad news: as soon as Numpy is used, icpc fails with errors related to code in `pythran/pythonic/include/types/ndarray.hpp` and `pythran/pythonic/types/ndarray.hpp` (see the attached log file [bug_icpc_pythran.log](https://github.com/serge-sans-paille/pythran/files/2519117/bug_icpc_pythran.log)).

```
/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/types/ndarray.hpp(1127): error: declaration is incompatible with function template "auto <unnamed>::pythonic::types::__ndarray::<unnamed>::_build_gexpr<N>::operator()(const E &, const S &...)->decltype((<expression>))" (declared at line 728 of "/panfs/panasas/cnt0022/egi2153/augier/Dev/pythran/pythran/pythonic/include/types/ndarray.hpp")
        auto _build_gexpr<N>::operator()(E const &a, S const &... slices)
```

In order to contact Intel people, we would need a minimal complete verifiable example.

However, the code is not exactly simple... and I don't understand what is the problem of icpc with this code.

@serge-sans-paille would you have time to write such example ?

Note that your example in https://software.intel.com/en-us/forums/intel-c-compiler/topic/623633 now compiles with icpc >= 17.1.

**Comment by serge-sans-paille** [comment]
@paugier: the following code does not compile with icpc 18

```sh
> icpc --version
icpc (ICC) 18.0.0 20170811
```

Not-compiling version

```c++
template <class E> struct adaptor {
  E arg;
  adaptor(E arg) : arg(arg) {}
};

template <int, class E> struct functor;

template <class E> struct functor<0, E> {
  using result_type = E;
  E operator()(E const &a); };

template <class E> struct functor<0, adaptor<E>> {
  using result_type = adaptor<typename functor<0, E>::result_type>;
  adaptor<typename functor<0, E>::result_type> operator()(adaptor<E> const &a);
};

template <class E>
adaptor<typename functor<0, E>::result_type> functor<0, adaptor<E>>::operator()(adaptor<E> const &a) {
  return functor<0, E>{}(a.arg);
}

template <class E> E functor<0, E>::operator()(E const &a) {
  return a;
}

void foo() { functor<0, adaptor<int>>{}(3); }
```

compiling version

```c++
template <class E> struct adaptor {
  E arg;
  adaptor(E arg) : arg(arg) {}
};

template <int, class E> struct functor;

template <class E> struct functor<0, E> {
  using result_type = E;
  E operator()(E const &a); };

template <class E> struct functor<0, adaptor<E>> {
  using result_type = adaptor<typename functor<0, E>::result_type>;
  result_type operator()(adaptor<E> const &a);
};

template <class E>
typename functor<0, adaptor<E>>::result_type functor<0, adaptor<E>>::operator()(adaptor<E> const &a) {
  return functor<0, E>{}(a.arg);
}

template <class E> E functor<0, E>::operator()(E const &a) {
  return a;
}

void foo() { functor<0, adaptor<int>>{}(3); }


```

**Comment by boegel** [comment]
Any updates on this?

I noticed that the non-compiling example is still problematic with the latest Intel compiler 2021.4.0:

```
$ icpc -V
Intel(R) C++ Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.4.0 Build 20210910_000000
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.

$ icpc -c pythran-test-1.cc
pythran-test-1.cc(18): error: declaration is incompatible with "adaptor<functor<0, E>::result_type> functor<0, adaptor<E>>::operator()(const adaptor<E> &)" (declared at line 14)
  adaptor<typename functor<0, E>::result_type> functor<0, adaptor<E>>::operator()(adaptor<E> const &a) {
                                                                       ^

compilation aborted for pythran-test-1.cc (code 2)
```

There's also a problem that pops up when trying to build `scipy` 1.7.1 with Intel compilers, which requires `pythran` by default; see https://github.com/scipy/scipy/issues/14935.

**Comment by samcom12** [comment]
Getting the same error. waiting for fix

**Comment by serge-sans-paille** [comment]
@boegel : there's no CI for icc, and I don't have one to run the test. Can you still share a minimal failing `.py`?

**Comment by serge-sans-paille** [comment]
Now that https://github.com/serge-sans-paille/pythran/pull/2003 has been merged, this should behave correctly. If not, I should broaden the set of files compiled by icc. @boegel / @paugier can you confirm?

**Comment by paugier** [comment]
I should be able to try again in few days.

**Comment by paugier** [comment]
I was finally able to check. Many files now compile fine with icc, which is really great! But I get an issue with this code:

```
# pythran export compute_increments_dim1(float64[:, :], int)

def compute_increments_dim1(var, irx):
    'Compute the increments of var over the dim 1.'
    n1 = var.shape[1]
    n1new = (n1 - irx)
    # bug for gast 0.4.0 (https://github.com/serge-sans-paille/gast/issues/48)                                                                                                          
    inc_var = (var[:, irx:n1] - var[:, 0:n1new])
    return inc_var
```

Very long error log with different kinds of `pythran-0.11.0-py3.8.egg/pythran/pythonic/include/types/numpy_gexpr.hpp(256): note: this candidate was rejected because at least one template argument could not be deduced`...

Could we add this code as a test for icc and see if this problem can be reproduce in the CI?

It's for icc (ICC) 19.1.0.166
