### ISSUE TITLE
pythran dprod.py error

### ISSUE THREAD

**Issue by wyk-qyf** [serge-sans-paille/pythran#669]
Using linuxmint newest 
follow the instruction: 

    Gather dependencies:

    Pythran depends on a few Python modules and several C++ libraries. On a debian-like platform, run:

    $> sudo apt-get install libgmp-dev libblas-dev
    $> sudo apt-get install python-dev python-ply python-networkx python-numpy

    Use easy_install or pip:

    $> pip install pythran

then follow this :  
Basic Usage

A simple pythran input could be dprod.py:

"""
Naive dotproduct! Pythran supports numpy.dot
"""
#pythran export dprod(int list, int list)
def dprod(l0,l1):
    """WoW, generator expression, zip and sum."""
    return sum(x * y for x, y in zip(l0, l1))

To turn it into a native module, run:

$> pythran dprod.py

ERROR:
mint@mint ~/test $ pythran dprod.py
WARNING: Disabling color, you really want to install colorlog.
Traceback (most recent call last):
  File "/usr/local/bin/pythran", line 7, in <module>
    from pythran.run import run
  File "/usr/local/lib/python2.7/dist-packages/pythran/__init__.py", line 39, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/usr/local/lib/python2.7/dist-packages/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx
  File "/usr/local/lib/python2.7/dist-packages/pythran/backend.py", line 8, in <module>
    from pythran.analyses import ArgumentEffects, BoundExpressions, Dependencies
  File "/usr/local/lib/python2.7/dist-packages/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/usr/local/lib/python2.7/dist-packages/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/usr/local/lib/python2.7/dist-packages/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/usr/local/lib/python2.7/dist-packages/pythran/tables.py", line 3056, in <module>
    defaults=(1, None)
  File "/usr/local/lib/python2.7/dist-packages/pythran/intrinsic.py", line 138, in __init__
    super(ConstFunctionIntr, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pythran/intrinsic.py", line 93, in __init__
    super(FunctionIntr, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pythran/intrinsic.py", line 57, in __init__
    [to_ast(d) for d in kwargs.get('defaults', [])])
  File "/usr/local/lib/python2.7/dist-packages/pythran/conversion.py", line 86, in to_ast
    numpy.bool_, numpy._globals._NoValue)
AttributeError: 'module' object has no attribute '_globals'
mint@mint ~/test $

**Comment by wyk-qyf** [comment]
I have googled two days. 
please help me!

**Comment by serge-sans-paille** [comment]
can you ``pip install -U numpy`` and try again?

**Comment by artas360** [comment]
Looks like the version of numpy used by Mint (`4092a9e160cc247a4a45724579a0c829733688ca`) does not have a `globals.py` file and `_NoValue` is defined in  `init.py`.
Just replacing `numpy._globals._NoValue` by `numpy._NoValue` in `/usr/local/lib/python2.7/dist-packages/pythran/conversion.py` should fix the problem.

**Comment by serge-sans-paille** [comment]
Yup, could you track the numpy version and add the correct if
numpy.version > ... test somewhere?

**Comment by artas360** [comment]
It's 11.0, but I think just using `numpy._NoValue` instead of `numpy._globals._NoValue` might be sufficient. It seems to work with version 1.11 and above. I'll try with earlier version, but what versions of numpy is Pythran supposed to support?

**Comment by serge-sans-paille** [comment]
On Sat, May 27, 2017 at 11:56:59AM -0700, Merlini Adrien wrote:
> It's 11.0, but I think just using `numpy._NoValue` instead of `numpy._globals._NoValue` might be sufficient. It seems to work with version 1.11 and above. I'll try with earlier version, but what versions of numpy is Pythran supposed to support?

Only last version, but I'll accept your PR if it supports older version
as well :-)

**Comment by artas360** [comment]
master doesn't need any modifs since it does not seem to be using `numpy._NoValue`. 
I don't see any `0.8` branch  (version on pythonhosted) to fix on the repo, so updating the pip version to master's status would be enough, if it's ready for release. What do you think?

**Comment by serge-sans-paille** [comment]
On Tue, May 30, 2017 at 12:06:57PM -0700, Merlini Adrien wrote:
> master doesn't need any modifs since it does not seem to be using `numpy._NoValue`. 
> I don't see any `0.8` branch  (version on pythonhosted) to fix on the repo, so updating the pip version to master's status would be enough, if it's ready for release. What do you think?

ooops (TM) I didn't remember it was fixed on master. I plan to do a
release near July...

**Comment by serge-sans-paille** [comment]
Commit integrated and release some months ago
