### ISSUE TITLE
test_complex_conj fails with xsimd 8

### ISSUE THREAD

**Issue by drew-parsons** [serge-sans-paille/pythran#1943]
Running pythran tests, all pass with xsimd 7.6 (xtensor 0.23).

But with xsimd 8.0.3 (xtensor 0.24.0), TestBase.test_complex_conj fails, with the following errors collected in stderr:
```
In file included from /projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/__dispatch__/conjugate.hpp:4,
                 from /tmp/tmpytnjb9kb.cpp:10:
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:22:36: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class A> class xsimd::batch’
   22 |     xsimd::batch<std::complex<T>, N>
      |                                    ^
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:22:36: note:   expected a type, got ‘N’
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:23:46: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class A> class xsimd::batch’
   23 |     conjugate(xsimd::batch<std::complex<T>, N> const &v)
      |                                              ^
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:23:46: note:   expected a type, got ‘N’
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp: In function ‘int {anonymous}::pythonic::numpy::wrapper::conjugate(const int&)’:
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:25:25: error: no matching function for call to ‘conj(const int&)’
   25 |       return xsimd::conj(v);
      |              ~~~~~~~~~~~^~~
In file included from /usr/include/xsimd/xsimd.hpp:24,
                 from /projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:8,
                 from /projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/__dispatch__/conjugate.hpp:4,
                 from /tmp/tmpytnjb9kb.cpp:10:
/usr/include/xsimd/types/xsimd_api.hpp:392:35: note: candidate: ‘template<class A, class T> xsimd::complex_batch_type_t<xsimd::batch<T, A> > xsimd::conj(const xsimd::batch<T, A>&)’
  392 | complex_batch_type_t<batch<T, A>> conj(batch<T, A> const& z) {
      |                                   ^~~~
/usr/include/xsimd/types/xsimd_api.hpp:392:35: note:   template argument deduction/substitution failed:
In file included from /projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/__dispatch__/conjugate.hpp:4,
                 from /tmp/tmpytnjb9kb.cpp:10:
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:25:25: note:   mismatched types ‘const xsimd::batch<T, A>’ and ‘const int’
   25 |       return xsimd::conj(v);
      |              ~~~~~~~~~~~^~~
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp: At global scope:
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:28:22: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class A> class xsimd::batch’
   28 |     xsimd::batch<T, N> conjugate(xsimd::batch<T, N> const &v)
      |                      ^
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:28:22: note:   expected a type, got ‘N’
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:28:51: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class A> class xsimd::batch’
   28 |     xsimd::batch<T, N> conjugate(xsimd::batch<T, N> const &v)
      |                                                   ^
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:28:51: note:   expected a type, got ‘N’
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:28:24: error: redefinition of ‘template<class T, long unsigned int N> int {anonymous}::pythonic::numpy::wrapper::conjugate(const int&)’
   28 |     xsimd::batch<T, N> conjugate(xsimd::batch<T, N> const &v)
      |                        ^~~~~~~~~
/projects/python/build/pythran/.pybuild/cpython3_3.9_pythran/build/pythran/pythonic/include/numpy/conjugate.hpp:23:5: note: ‘template<class T, long unsigned int N> int {anonymous}::pythonic::numpy::wrapper::conjugate(const int&)’ previously declared here
   23 |     conjugate(xsimd::batch<std::complex<T>, N> const &v)
      |     ^~~~~~~~~
```

**Comment by serge-sans-paille** [comment]
Which version of pythran is that? It seems to pass correctly on master.
Support for xsimd 8> got introduced in 418bd3e8cd295bd60cdc24fca564dfd3e4614e3d which is not included in pythran 0.10.0.

**Comment by drew-parsons** [comment]
This is pythran 0.10.0 
(0.10.0+ds-1 for debian packaging, https://salsa.debian.org/python-team/packages/pythran ).
Sounds like you've already fixed it. I'll try applying 418bd3e .

**Comment by serge-sans-paille** [comment]
Wouldn't that be easier if I just do a release next week?

**Comment by drew-parsons** [comment]
In a sense :)  But no rush.  pythran is a new package for debian, it's in the NEW queue (https://ftp-master.debian.org/new.html). It may take some time to get processed and placed into the package archive. So it won't be available to our users until that is done anyway.

**Comment by serge-sans-paille** [comment]
ok, it's good to have xsimd 8 in a new release anyway. And no, xsimd 8 and xsimd 7 are not compatible (thus the major version bump)

**Comment by serge-sans-paille** [comment]
@drew-parsons I believe we can close that issue: the new release depends on xsimd 8, and that should be enough for you, correct?

**Comment by drew-parsons** [comment]
That's fine for me, thanks Serge.
