### PR TITLE
Improve lambda removal

### LINKED ISSUE #1963: Info message: bailing out due to 'builtins' having no 'pythran' attribute
I've been using pythran in my personal project for a while.

I'm trying to compile a large [file](https://www.dropbox.com/s/3vcopxkk543ydok/GLNetEISimLib.py?dl=0)
using pythran 0.11.0,

`pythran GLNetEISimLib.py -o GLNetEISimLib.so -Ofast -march=native -v`

and it is saying

> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'

Is this message anything of concern? It seems pythran is going into an infinite loop, because this message is being displayed many times.

I had been using pythran 0.9.9.dev from 2021-01-03, and I don't remember seeing this INFO warning. It took a very long time to compile though (about 4h).

I'm using Python 3.8.10 which comes by default in Ubuntu 20.04.

### **UPDATE**

The compilation with pythran 0.11.0 actually crashed, but succeeded to compile with pythran 0.9.9.dev0.

**Here is the output of the pythran 0.11.0 error with -v parameter:**

> INFO:      sys file exists: /usr/local/lib/python3.8/dist-packages/pythran/pythran.cfg

> INFO: platform file exists: /usr/local/lib/python3.8/dist-packages/pythran/pythran-linux.cfg
> WARNING:     user file does not exist: /home/mgirardi/.pythranrc
> INFO: pythranrc section [pythran] is valid and options are correct
> INFO: pythranrc section [typing] is valid and options are correct
> INFO: pythranrc section [compiler] is valid and options are correct
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> INFO: During constant folding, bailing out due to: module 'builtins' has no attribute 'pythran'
> WARNING: Exporting function 'save_spk_data' that modifies its List argument. Beware that this argument won't be modified at Python call site
> running build_ext
> DEBUG: new_compiler returns <class 'distutils.unixccompiler.UnixCCompiler'>
> building 'GLNetEISimLib' extension
> INFO: C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC
> 
> INFO: compile options: '-DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.8/dist-packages/pythran -I/usr/local/lib/python3.8/dist-packages/numpy/core/include -I/usr/include/python3.8 -c'
> extra options: '-std=c++11 -fno-math-errno -fvisibility=hidden -fno-wrapv -Wno-unused-function -Wno-int-in-bool-context -Wno-unknown-warning-option -Ofast -march=native'
> INFO: x86_64-linux-gnu-gcc: /tmp/tmp9xoywpql.cpp
> /tmp/tmp9xoywpql.cpp: In member function ‘typename __pythran_GLNetEISimLib::RunSimulation_adapt::type<argument_type0, argument_type1, argument_type2, argument_type3, argument_type4, argument_type5, argument_type6, argument_type7, argument_type8, argument_type9, argument_type10, argument_type11, argument_type12, argument_type13, argument_type14, argument_type15, argument_type16, argument_type17, argument_type18, argument_type19, argument_type20, argument_type21, argument_type22, argument_type23, argument_type24, argument_type25, argument_type26, argument_type27, argument_type28, argument_type29, argument_type30, argument_type31, argument_type32>::result_type __pythran_GLNetEISimLib::RunSimulation_adapt::operator()(argument_type0&&, argument_type1&&, argument_type2&&, argument_type3&&, argument_type4&&, argument_type5&&, argument_type6&&, argument_type7&&, argument_type8&&, argument_type9&&, argument_type10&&, argument_type11&&, argument_type12&&, argument_type13&&, argument_type14&&, argument_type15&&, argument_type16&&, argument_type17&&, argument_type18&&, argument_type19&&, argument_type20&&, argument_type21&&, argument_type22&&, argument_type23&&, argument_type24&&, argument_type25&&, argument_type26&&, argument_type27&&, argument_type28&&, argument_type29&&, argument_type30&&, argument_type31&&, argument_type32&&) const’:
> /tmp/tmp9xoywpql.cpp:6185:72: warning: typedef ‘__type584’ locally defined but not used [-Wunused-local-typedefs]
>  6185 |     typedef container<typename std::remove_reference<__type583>::type> __type584;
>       |                                                                        ^~~~~~~~~
> x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1plus
> compilation terminated.
> WARNING: Compilation error, trying hard to find its origin...
> Compilation error, trying hard to find its origin...
> WARNING: Nop, I'm going to flood you with C++ errors!
> Nop, I'm going to flood you with C++ errors!
> CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!
> E: error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.8/dist-packages/pythran -I/usr/local/lib/python3.8/dist-packages/numpy/core/include -I/usr/include/python3.8 -c /tmp/tmp9xoywpql.cpp -o /tmp/tmpvmlgpicy/tmp/tmp9xoywpql.o -std=c++11 -fno-math-errno -fvisibility=hidden -fno-wrapv -Wno-unused-function -Wno-int-in-bool-context -Wno-unknown-warning-option -Ofast -march=native" failed with exit status 1
> Cover me Jack. Jack? Jaaaaack!!!!
> E: error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.8/dist-packages/pythran -I/usr/local/lib/python3.8/dist-packages/numpy/core/include -I/usr/include/python3.8 -c /tmp/tmp9xoywpql.cpp -o /tmp/tmpvmlgpicy/tmp/tmp9xoywpql.o -std=c++11 -fno-math-errno -fvisibility=hidden -fno-wrapv -Wno-unused-function -Wno-int-in-bool-context -Wno-unknown-warning-option -Ofast -march=native" failed with exit status 1

And here is the output of the pythran 0.9.9.dev0 with -v:

> INFO:      sys file exists: /usr/local/lib/python3.8/dist-packages/pythran/pythran.cfg
> INFO: platform file exists: /usr/local/lib/python3.8/dist-packages/pythran/pythran-linux.cfg
> WARNING:     user file does not exist: /home/mgirardi/.pythranrc
> INFO: pythranrc section [pythran] is valid and options are correct
> INFO: pythranrc section [typing] is valid and options are correct
> INFO: pythranrc section [compiler] is valid and options are correct
> WARNING: Exporting function 'save_spk_data' that modifies its List argument. Beware that this argument won't be modified at Python call site
> running build_ext
> DEBUG: new_compiler returns <class 'distutils.unixccompiler.UnixCCompiler'>
> building 'GLNetEISimLib' extension
> INFO: C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC
> 
> INFO: compile options: '-DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.8/dist-packages/pythran -I/usr/local/lib/python3.8/dist-packages/numpy/core/include -I/usr/include/python3.8 -c'
> extra options: '-std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -Ofast -march=native'
> INFO: x86_64-linux-gnu-gcc: /tmp/tmpires7i2y.cpp
> INFO: x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 /tmp/tmpqvir8ebt/tmp/tmpires7i2y.o -L/usr/lib -o /tmp/tmp4sk9k4dl/GLNetEISimLib.cpython-38-x86_64-linux-gnu.so -fvisibility=hidden -Wl,-strip-all -Ofast -march=native
> INFO: Generated module: GLNetEISimLib
> INFO: Output: GLNetEISimLib.so

### PR DESCRIPTION
**Pull request by serge-sans-paille**
- recognize common operator.*
- avoid creating the same lambda twice

Fix #1963

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @jeanlaroche this may have a positive impact on your build compile time too

**Comment by jeanlaroche** [comment]
> cc @jeanlaroche this may have a positive impact on your build compile time too

I'm going to give it a shot asap!
